language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python3 train.py --sys=local --hparams=ppo_cartpole --train_episodes=10 --render=False
  